on:
  push:
    branches:
      - deploy-to-gcp

name: Deploy to Google App Engine

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '10'

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      # - name: Install
      #   run: npm install

      # - name: Build
      #   run: npm run gcp-build
    
      - name: Deploy to App Engine
        run: gcloud app deploy --quiet